version: '2'

services:
    adultseccomp:
        build: .
        cap_add:
            - SYS_PTRACE
        security_opt:
          - seccomp:unconfined
          - apparmor:unconfined
        privileged: true
        ports:
            - "3000:3000"