version: '3'
services:
  bfi:
    build:
      context: .
    working_dir: /home/pwn
    container_name: bfi
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9001:9001"
    entrypoint: /etc/init.sh
