/********************************************************************
 *   This C program was generated by spl2c, the Shakespeare to C    *
 *          converter by Jon Åslund and Karl Hasselström.           *
 ********************************************************************/

/* libspl definitions and function prototypes */
#include <spl.h>
#include <stdlib.h>
#include <stdio.h>

int main(void)
{
  /******************************************************************
   * THIS IS THE PLAY THAT ENCODES THE PAST                         *
   ******************************************************************/
  
  CHARACTER *romeo;                       /* a young programmer from a time long ago */
  CHARACTER *juliet;                      /* a beautiful woman with a memory disorder */
  
  int comp1, comp2;
  
  global_initialize();
  
  romeo = initialize_character("Romeo");
  juliet = initialize_character("Juliet");
  
  act_i:                                  /* The beginning */
  
  act_i_scene_i:                          /* In a processor , long long ago */
  
  enter_scene(10, romeo);
  enter_scene(10, juliet);
  
  act_i_scene_ii:                         /* The start of a never ending tale */
  
  activate_character(18, juliet);
  assign(16, second_person, int_sub(15, 2*2*2*2*2*2*1, 1));
  
  activate_character(21, romeo);
  push(19, second_person, value_of(19, first_person));
  
  activate_character(26, juliet);
  assign(24, second_person, int_add(22, 1, int_add(23, 2*2*2*2*1, 2*2*2*2*2*1)));
  
  activate_character(29, romeo);
  push(27, second_person, value_of(27, first_person));
  
  activate_character(34, juliet);
  assign(32, second_person, int_mul(30, int_add(30, 1, 2*1), int_add(31, 2*1, 2*2*2*2*2*1)));
  
  activate_character(37, romeo);
  push(35, second_person, value_of(35, first_person));
  
  activate_character(42, juliet);
  assign(40, second_person, int_add(38, 2*1, int_add(39, 2*2*2*2*2*1, 2*2*2*2*2*2*1)));
  
  activate_character(45, romeo);
  push(43, second_person, value_of(43, first_person));
  
  activate_character(51, juliet);
  assign(49, second_person, int_sub(46, 2*2*2*2*2*2*1, int_add(48, 1, 2*2*2*1)));
  
  activate_character(54, romeo);
  push(52, second_person, value_of(52, first_person));
  
  activate_character(59, juliet);
  assign(57, second_person, int_sub(55, 2*2*2*2*2*2*2*1, 2*2*1));
  
  activate_character(62, romeo);
  push(60, second_person, value_of(60, first_person));
  
  activate_character(68, juliet);
  assign(66, second_person, int_add(63, int_add(63, 1, 2*2*1), int_add(64, 2*2*2*2*2*1, 2*2*2*2*2*2*1)));
  
  activate_character(71, romeo);
  push(69, second_person, value_of(69, first_person));
  
  activate_character(76, juliet);
  assign(74, second_person, int_sub(72, 2*2*2*2*2*2*1, 2*2*1));
  
  activate_character(79, romeo);
  push(77, second_person, value_of(77, first_person));
  
  activate_character(84, juliet);
  assign(82, second_person, int_sub(80, 2*2*2*2*2*2*1, 2*2*1));
  
  activate_character(87, romeo);
  push(85, second_person, value_of(85, first_person));
  
  act_i_scene_iii:                        /* The breather */
  
  activate_character(95, juliet);
  assign(93, second_person, int_add(90, 2*2*2*1, int_add(91, 2*2*2*2*2*1, 2*2*2*2*2*2*1)));
  
  activate_character(98, romeo);
  push(96, second_person, value_of(96, first_person));
  
  activate_character(104, juliet);
  assign(102, second_person, int_add(99, 2*1, int_sub(100, 2*2*2*2*2*2*2*1, 2*2*2*2*1)));
  
  activate_character(107, romeo);
  push(105, second_person, value_of(105, first_person));
  
  act_i_scene_iv:                         /* The breather */
  
  activate_character(114, juliet);
  assign(112, second_person, int_sub(110, 2*2*2*2*2*2*2*1, int_add(111, 2*1, 2*2*2*2*1)));
  
  activate_character(117, romeo);
  push(115, second_person, value_of(115, first_person));
  
  activate_character(121, juliet);
  assign(119, second_person, int_add(118, 1, 2*2*2*2*2*2*2*1));
  
  activate_character(124, romeo);
  push(122, second_person, value_of(122, first_person));
  
  activate_character(129, juliet);
  assign(127, second_person, int_add(125, 2*1, int_sub(126, 2*2*2*2*2*2*2*1, 2*2*2*1)));
  
  activate_character(132, romeo);
  push(130, second_person, value_of(130, first_person));
  
  activate_character(138, juliet);
  assign(136, second_person, int_sub(133, int_add(133, 1, 2*2*2*2*2*2*2*1), int_add(135, 2*2*1, 2*2*2*2*1)));
  
  activate_character(141, romeo);
  push(139, second_person, value_of(139, first_person));
  
  activate_character(145, juliet);
  assign(143, second_person, int_add(142, 2*2*1, 2*2*2*2*2*2*1));
  
  activate_character(148, romeo);
  push(146, second_person, value_of(146, first_person));
  
  activate_character(152, juliet);
  assign(150, second_person, int_add(149, 2*2*1, 2*2*2*2*2*2*1));
  
  activate_character(155, romeo);
  push(153, second_person, value_of(153, first_person));
  
  activate_character(160, juliet);
  assign(158, second_person, int_sub(156, 2*2*2*2*2*2*2*1, 2*2*2*2*1));
  
  activate_character(163, romeo);
  push(161, second_person, value_of(161, first_person));
  
  activate_character(168, juliet);
  assign(166, second_person, int_add(164, 2*2*2*1, int_sub(165, 2*2*2*2*2*2*1, 1)));
  
  activate_character(171, romeo);
  push(169, second_person, value_of(169, first_person));
  
  act_i_scene_v:                          /* The breather */
  
  activate_character(178, juliet);
  assign(176, second_person, int_add(174, 1, int_add(174, 2*2*2*1, 2*2*2*2*2*2*1)));
  
  activate_character(181, romeo);
  push(179, second_person, value_of(179, first_person));
  
  activate_character(186, juliet);
  assign(184, second_person, int_add(182, 2*1, 2*2*2*2*2*2*2*1));
  
  activate_character(189, romeo);
  push(187, second_person, value_of(187, first_person));
  
  activate_character(194, juliet);
  assign(192, second_person, int_add(190, 1, int_add(191, 2*2*2*1, 2*2*2*2*2*2*1)));
  
  activate_character(197, romeo);
  push(195, second_person, value_of(195, first_person));
  
  act_i_scene_vi:                         /* The breather */
  
  activate_character(203, juliet);
  assign(201, second_person, int_add(200, 2*1, 2*2*2*2*2*2*2*1));
  
  activate_character(206, romeo);
  push(204, second_person, value_of(204, first_person));
  
  activate_character(211, juliet);
  assign(209, second_person, int_add(207, 2*2*2*1, int_sub(208, 2*2*2*2*2*2*1, 1)));
  
  activate_character(214, romeo);
  push(212, second_person, value_of(212, first_person));
  
  activate_character(220, juliet);
  assign(218, second_person, int_add(215, int_add(215, 1, 2*2*1), int_add(216, 2*2*2*1, 2*2*2*2*2*2*1)));
  
  activate_character(223, romeo);
  push(221, second_person, value_of(221, first_person));
  
  activate_character(228, juliet);
  assign(226, second_person, int_add(224, 2*2*1, int_add(225, 2*2*2*1, 2*2*2*2*2*2*1)));
  
  activate_character(231, romeo);
  push(229, second_person, value_of(229, first_person));
  
  activate_character(236, juliet);
  assign(234, second_person, int_add(232, 1, int_sub(233, 2*2*2*2*2*2*2*1, 2*2*2*1)));
  
  activate_character(239, romeo);
  push(237, second_person, value_of(237, first_person));
  
  activate_character(244, juliet);
  assign(242, second_person, int_add(240, 2*2*2*2*1, int_sub(241, 2*2*2*2*2*2*1, 2*1)));
  
  activate_character(247, romeo);
  push(245, second_person, value_of(245, first_person));
  
  act_i_scene_vii:                        /* The breather */
  
  activate_character(254, juliet);
  assign(252, second_person, int_add(250, 2*1, int_add(251, 2*2*2*2*1, 2*2*2*2*2*2*2*1)));
  
  activate_character(257, romeo);
  push(255, second_person, value_of(255, first_person));
  
  activate_character(263, juliet);
  assign(261, second_person, int_add(258, int_add(258, 1, 2*2*1), int_add(259, 2*2*2*1, 2*2*2*2*2*2*1)));
  
  activate_character(266, romeo);
  push(264, second_person, value_of(264, first_person));
  
  activate_character(271, juliet);
  assign(269, second_person, int_add(267, 2*1, int_add(268, 2*2*2*1, 2*2*2*2*2*2*2*1)));
  
  activate_character(274, romeo);
  push(272, second_person, value_of(272, first_person));
  
  activate_character(279, juliet);
  assign(277, second_person, int_sub(275, 2*2*2*2*2*2*2*1, 2*1));
  
  activate_character(282, romeo);
  push(280, second_person, value_of(280, first_person));
  
  activate_character(288, juliet);
  assign(286, second_person, int_add(283, int_add(283, 1, 2*2*1), int_add(284, 2*2*2*2*1, 2*2*2*2*2*2*2*1)));
  
  activate_character(291, romeo);
  push(289, second_person, value_of(289, first_person));
  
  activate_character(296, juliet);
  assign(294, second_person, int_add(292, 1, int_add(292, 2*2*2*2*1, 2*2*2*2*2*2*1)));
  
  activate_character(299, romeo);
  push(297, second_person, value_of(297, first_person));
  
  activate_character(305, juliet);
  assign(303, second_person, int_mul(300, int_add(300, 1, 2*2*1), int_sub(301, 2*2*2*2*2*1, 1)));
  
  activate_character(308, romeo);
  push(306, second_person, value_of(306, first_person));
  
  activate_character(312, juliet);
  assign(310, second_person, int_add(309, 2*1, 2*2*2*2*2*2*2*1));
  
  activate_character(315, romeo);
  push(313, second_person, value_of(313, first_person));
  
  act_i_scene_viii:                       /* The breather */
  
  activate_character(323, juliet);
  assign(321, second_person, int_add(318, int_sub(318, 2*2*2*2*2*1, 1), int_sub(320, 2*2*2*2*2*2*1, 2*2*1)));
  
  activate_character(326, romeo);
  push(324, second_person, value_of(324, first_person));
  
  activate_character(332, juliet);
  assign(330, second_person, int_add(327, int_add(327, 1, 2*1), int_add(328, 2*2*2*2*1, 2*2*2*2*2*2*2*1)));
  
  activate_character(335, romeo);
  push(333, second_person, value_of(333, first_person));
  
  activate_character(341, juliet);
  assign(339, second_person, int_add(336, int_add(336, 2*1, 2*2*1), int_add(337, 2*2*2*2*1, 2*2*2*2*2*2*1)));
  
  activate_character(344, romeo);
  push(342, second_person, value_of(342, first_person));
  
  activate_character(350, juliet);
  assign(348, second_person, int_add(345, int_add(345, 1, 2*1), int_add(346, 2*2*2*1, 2*2*2*2*2*2*2*1)));
  
  activate_character(353, romeo);
  push(351, second_person, value_of(351, first_person));
  
  activate_character(358, juliet);
  assign(356, second_person, int_add(354, 2*2*2*1, 2*2*2*2*2*1));
  //goto act_i_scene_ii;
  
  act_i_scene_ix:                         /* The start of something new */
  
  activate_character(364, juliet);
  assign(362, second_person, int_sub(361, value_of(361, second_person), 1));
  
  activate_character(368, romeo);
  pop(365, second_person);
  assign(366, second_person, int_sub(365, value_of(366, second_person), value_of(366, first_person)));
  
  activate_character(371, juliet);
  push(369, second_person, value_of(369, first_person));
  
  activate_character(375, romeo);
  comp1 = value_of(372, first_person);
  comp2 = int_sub(372, 1, 1);
  truth_flag = (comp1 > comp2);
  
  activate_character(378, juliet);
  if (truth_flag) {
    goto act_i_scene_ix;
  }
  
  exit_scene_all(378);
  
  return 0;
}
