version: '3'
services:
  pwn1:
    build:
      context: .
    working_dir: /home/pwn
    container_name: pwn1
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9000:9000"
    entrypoint: /etc/init.sh
